project:
  type: website

website:
  title: "Afshan's Portfolio"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Misannotated lncRNAs"
        contents:
          - misannotated_lncrnas/Overview.ipynb
      - section: "fastai"
      - section: "Notes"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
